### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by uniBruce** [TimoBolkart/voca#1]
Hi, thanks for the amazing work, but I have not found the dataset link. Have you made it publicly available yet?

**Comment by anuragranj** [comment]
Yes, you would need to sign in here and agree to the license terms.
https://voca.is.tue.mpg.de/

**Comment by uniBruce** [comment]
> Yes, you would need to sign in here and agree to the license terms.
> https://voca.is.tue.mpg.de/

Yeah, I noticed that after I left this message. Thank you all the same.
