### ISSUE TITLE
question about the learning rate decay

### ISSUE THREAD

**Issue by brooks0519** [TimoBolkart/voca#102]
Hello, Thanks for your great work, recently, I have do some work to replace deepspeech0.1.0 to adapt live audio streaming inference. So I retrain the voca model, but I found the learning rate is always 0.0001,  I want to know have you ever use decay learning rate? and the effect of different learning rate?  thanks again

**Comment by TimoBolkart** [comment]
No, we did not decay the learning rate and we did not investigate the effect of different learning rates. If you find some better training strategy, I would be happy to learn about it.
