### ISSUE TITLE
Which equipment is needed to collect data and how can I buy it?

### ISSUE THREAD

**Issue by liushoukuai** [TimoBolkart/voca#104]

**Comment by TimoBolkart** [comment]
We captured the VOCASET with a calibrated multi-view stereo setup provided by 3dMD. Details see below. 

![image](https://user-images.githubusercontent.com/26549953/194268163-6571ed0f-66d3-42c7-aad4-c6e02ca21001.png)

**Comment by liushoukuai** [comment]
Thank you for your answer, may I ask how to process the scanned meshes into the same topology.

**Comment by liushoukuai** [comment]
> We captured the VOCASET with a calibrated multi-view stereo setup provided by 3dMD. Details see below.
> 
> ![image](https://user-images.githubusercontent.com/26549953/194268163-6571ed0f-66d3-42c7-aad4-c6e02ca21001.png)

Thank you for your answer, may I ask how to process the scanned meshes into the same topology.

**Comment by liushoukuai** [comment]
Thank you for your answer, may I ask how to process the scanned meshes into the same topology. 
















At 2022-10-06 16:56:26, "TimoBolkart" ***@***.***> wrote:

We captured the VOCASET with a calibrated multi-view stereo setup provided by 3dMD. Details see below.
