### ISSUE TITLE
How to add textured template ? does it only supports .ply and .obj ? not able to add textured obj/ply

### ISSUE THREAD

**Issue by Mayankcha** [TimoBolkart/voca#12]

**Comment by TimoBolkart** [comment]
The output of VOCA is a ply or obj geometry file without texture. The used Mesh package should however supports textured meshes. You can just load a textured meh in FLAME topology and apply the texture to each output frame

**Comment by snehil-vaidh** [comment]
So you mean to say we need to apply flame code to get a flame topology on textured object and then put in under voca to get the textured results

**Comment by TimoBolkart** [comment]
VOCA animates meshes in FLAME topology. This means, each output mesh of VOCA is in FLAME topology. You could just add another step before outputting each mesh that adds a texture to the mesh. Does this answer your question?

**Comment by fastcode3d** [comment]
> Yes thanq for your reply.! Can you suggest any source which can help me add texture to the mesh?
I have the same question. Have you solved your problem which add texture to the mesh?
