### ISSUE TITLE
the result contain the static face information  of training data when I use the model trained by myself,could you please tell me what I had missed?

### ISSUE THREAD

**Issue by zxc210** [TimoBolkart/voca#13]
hello,thanks for your sharing firstly. I found that the result of the model contain the static face information in the training data(I downloaded on the  MPI-IS/VOCASET) when i try to trained the model according to your paper:
such as the out put of '.obj' in the 'animation_output' folder will contain the face static features which  in the training data,the face static feature is change and is not the same as 'template/FLAME_sample.ply' when i set  '--condition_idx 3', 
Could you please tell me the reason of the question?
And I found the template as input such as "input_template: np.repeat(template.v[np.newaxis, :, :, np.newaxis], num_frames, axis=0)" when i  run run_voca.py，is it use to initialized the weights or it has another purpose?Could you please tell me the use of the template in training?

**Comment by TimoBolkart** [comment]
Given VOCASET, VOCA learns the mapping between a speech signal and the facial motion. The facial motion is modeled as additive offset from the static template mesh. To learn the motion offset during training, we subtract for each frame of each VOCASET sequence the static template and try to predict this from the audio window (the audio is processed in the same way as done in the provided test code). When outputting the meshes, the predicted motion is then added to the personalized template to obtain the talking head of the particular subject.

**Comment by zxc210** [comment]
> Given VOCASET, VOCA learns the mapping between a speech signal and the facial motion. The facial motion is modeled as additive offset from the static template mesh. To learn the motion offset during training, we subtract for each frame of each VOCASET sequence the static template and try to predict this from the audio window (the audio is processed in the same way as done in the provided test code). When outputting the meshes, the predicted motion is then added to the personalized template to obtain the talking head of the particular subject.

thank you !
You reply help me a lot !
