### ISSUE TITLE
After add eyeblink, the face twitches

### ISSUE THREAD

**Issue by hrWong** [TimoBolkart/voca#131]
Thank you for your outstanding work!
When I work `edit_sequences.py`, there is a blink but there is a face jerk, before that the lip movement was correct, what could be the cause of this and what should I do to correct it.Here is video

https://github.com/user-attachments/assets/37cbc095-aef3-406d-960b-d017acfc632e

**Comment by TimoBolkart** [comment]
Can you please show the result before applying the edit_sequence script? Assuming that the lip sync was indeed fine prior to the edit_sequence, and given that the output sequence has eye blinks, the problem likely comes from the [file parsing](https://github.com/TimoBolkart/voca/blob/6819cd88ff88621b240822dcfddd3f24f937f930/edit_sequences.py#L60). How are your sequence frames named? Can you please check that the sorted filenames in the script indeed correspond to the order of the sequence frames?

**Comment by hrWong** [comment]
Hi @TimoBolkart, Thank you for your reply. I have fixed the issue. The problem was [here](https://github.com/TimoBolkart/voca/blob/6819cd88ff88621b240822dcfddd3f24f937f930/edit_sequences.py#L105), after I replaced the npy file with the predicted vertices, the results were normal.
