### ISSUE TITLE
python: malloc.c:2401: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

### ISSUE THREAD

**Issue by rm2886** [TimoBolkart/voca#15]
After generating obj file from run_voca.py when visualizing those object and creating the video using visualize_sequence.py, and  I've got this error, it's like there is C compiler run-time memory allocation problem.

**python: malloc.c:2401: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.**

Thanks in Advance. ;)

**Comment by TimoBolkart** [comment]
Does this error occur when rendering the meshes, or when encoding the renderings to a video?

**Comment by rm2886** [comment]
@TimoBolkart when encoding the  rendering to a video

**Comment by TimoBolkart** [comment]
Are you able to use ffmpeg directly to encode the images to a video? In your terminal (with activated virtual environment) just run
ffmpeg -framerate '60' -i './animation_visualization/img/%05d.png' ./animation_visualization/video.mp4
This should encode the images to a video (ignoring audio for now). Does this work?

**Comment by TimoBolkart** [comment]
I assume the problem is solved due to missing response
