### ISSUE TITLE
visualize_sequence render failure: Could not open file : ./animation_visualization/img/*.png

### ISSUE THREAD

**Issue by yefeng1992** [TimoBolkart/voca#16]
OpenGL test failed: 
	stdout: failure

	stderr: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling

ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[image2 @ 0x1e9c0e0**] Could not open file : ./animation_visualization/img/*.png**
[image2 @ 0x1e9c0e0] Could not find codec parameters for stream 0 (Video: png, none(pc)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'prCould not open file : ./animation_visualization/img/*.pngobesize' options
./animation_visualization/img/*.png: could not find codec parameters
Input #0, image2, from './animation_visualization/img/*.png':
  Duration: 00:00:00.02, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: png, none(pc), 60 tbr, 60 tbn, 60 tbc
Guessed Channel Layout for  Input Stream #1.0 : mono

Why did mv.save did not save any *.png files in img folder? Thank you.

**Comment by TimoBolkart** [comment]
Did the model successfully output meshes before? Does only the rendering fail, or also the mesh output?

**Comment by greatgeekgrace** [comment]
@yefeng1992 I have the same problem. Have you solved it?

**Comment by TimoBolkart** [comment]
We updated the repository to Python 3. This allowed us to change the used openGL-based rendering to pyrender. This should resolve the openGL problems.
