### ISSUE TITLE
Issue about decoder

### ISSUE THREAD

**Issue by huybery** [TimoBolkart/voca#18]
The decoder of VOCA is ba fully connected layer with linear activation function, outputting the 5023 × 3 dimensional array, but how does the 50-dimensional data map to 5023x3 through the last full connection layer?  I hope the architecture here can be explained in more detail. Thank you.

**Comment by TimoBolkart** [comment]
The last layer is a fully connected layer (without any activation function) going from the 50-dimensional input to a 15069-dimensional output (= 5023 * 3). This output is then reshaped to dimension 5023 x 3.
