### ISSUE TITLE
Problem about out-of-range condition index

### ISSUE THREAD

**Issue by chaiyujin** [TimoBolkart/voca#19]
The model still works even if I give an out-of-range condition index, for exmaple 100. What will happen if the index is out of range?

**Comment by TimoBolkart** [comment]
I am sorry, but I don't understand where there is any problem. 

The input index goes into a tf.one_hot function which provides the one-hot encoding. For indices outside of the range it provides a zero vector. The model is not trained with conditions outside of the range and hence I would not recommend usage of out-of-range indices.

**Comment by chaiyujin** [comment]
I have to apologize for this question, because I'm not familiar with tf.one_hot.  I should just read tf documents.
Thanks for your time.
