### ISSUE TITLE
MPI/Mesh does't support Python 2.7 anymore

### ISSUE THREAD

**Issue by tobyclh** [TimoBolkart/voca#20]
Hi, the new update for the MPI/Mesh repository breaks on Python 2.7.
I can confirm that reverting to commit 1761d544686b3735991954947a8befa759891eb4 does fix the problem on my side. Please consider adding this to the readme/ add the mesh repo as a submodule.

Thanks!

**Comment by TimoBolkart** [comment]
Hi, thank you for the information. Can you please add an issue to the MPI/Mesh repo?

**Comment by tobyclh** [comment]
No problem!

**Comment by TimoBolkart** [comment]
I forked the version 1761d544686b3735991954947a8befa759891eb4 of the mesh package which was compatible with Python 2.7. This should do as temporary workaround until VOCA is ported to Python 3 as well

**Comment by yangbiaobiao500** [comment]
> Hi, thank you for the information. Can you please add an issue to the MPI/Mesh repo?

I have installed the mesh version you released for py27, but the problem still exists

 Found link https://pypi.tuna.tsinghua.edu.cn/packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl#sha256=c3ede34530e0e0b2381e7363aded78e0c33291654937e7373032fda04e8803e5 (from https://pypi.tuna.tsinghua.edu.cn/simple/pip/) (requires-python:>=2.6,!=3.0.*,!=3.1.*,!=3.2.*), version: 9.0.3
  Found link https://pypi.tuna.tsinghua.edu.cn/packages/c4/44/e6b8056b6c8f2bfd1445cc9990f478930d8e3459e9dbf5b8e2d2922d64d3/pip-9.0.3.tar.gz#sha256=7bf48f9a693be1d58f49f7af7e0ae9fe29fd671cde8a55e6edca3581c4ef5796 (from https://pypi.tuna.tsinghua.edu.cn/simple/pip/) (requires-python:>=2.6,!=3.0.*,!=3.1.*,!=3.2.*), version: 9.0.3
Given no hashes to check 131 links for project 'pip': discarding no candidates
