### ISSUE TITLE
is there any way to make it blink?

### ISSUE THREAD

**Issue by chikiuso** [TimoBolkart/voca#22]
Hi, thanks for your excellent work. Is there any way to make the head blink? thanks.

**Comment by TimoBolkart** [comment]
Hi, do you mean eye blink related to the audio, or just manual control to blink?

**Comment by chikiuso** [comment]
It think related to audio is difficult, how about manual control to blink? How could I do it on the .ply file, such as the FLAME_sample.ply? thanks!

**Comment by TimoBolkart** [comment]
FLAME has the capacity in the expression parameters to blink. Similar to the provided demos to change the identity dependent facial shape or head pose, I just added a demo to add eye blinks to a video sequence. This demo demonstrates how to use FLAME to manipulate the eyelids to blink. I hope this helps.

**Comment by chikiuso** [comment]
@TimoBolkart ,thanks for your help!!
