### ISSUE TITLE
Training data corrupted

### ISSUE THREAD

**Issue by wenbooliu** [TimoBolkart/voca#24]
<img width="456" alt="image" src="https://user-images.githubusercontent.com/19863062/70742128-b1813900-1cd1-11ea-9e52-247f230b6fa4.png">

Thanks a lot for this wonderful work! I am trying to train voca with given dataset, however I met the problem with training data. After unzip, I got only data_vert.npy. Is this the complete training data?

**Comment by TimoBolkart** [comment]
The trainingdata.zip contains multiple files, not only the data_verts.npy. Can you please try some other tool to unzip?

**Comment by wenbooliu** [comment]
Thanks a lot for quick response.
The problem is solved.
