### ISSUE TITLE
no module audiohandler

### ISSUE THREAD

**Issue by ak9250** [TimoBolkart/voca#3]
Traceback (most recent call last):
  File "run_voca.py", line 22, in <module>
    from utils.inference import inference
  File "/content/voca/utils/inference.py", line 26, in <module>
    from audio_handler import  AudioHandler
ModuleNotFoundError: No module named 'audio_handler'

**Comment by TimoBolkart** [comment]
You find the AudioHandler in /utils/audio_handler.py
Either call run_voca.py from the folder voca root folder or set the the python path accordingly
This should solve the problem

**Comment by ak9250** [comment]
the problem was actually need change line 26 needs to be changed to 
from utils.audio_handler import  AudioHandler
in inferency.py
also I am having trouble getting this to work in google colab, since the models are not public I cannot share the notebook here, can I send you a email to look over the colab notebook?

**Comment by TimoBolkart** [comment]
Did you actually manage to get it run in google colab?
