### ISSUE TITLE
How to add or controll expression in the template animation?

### ISSUE THREAD

**Issue by plmsmile** [TimoBolkart/voca#34]
I want to add some expressions when the template is talking. But now I am not sure how to add it. Thanks for your advice~

**Comment by TimoBolkart** [comment]
We provide a demo (edit_sequences.py) to change facial shape for an animation. For this, please look into alter_sequence_shape within the edit_sequence.py line 150:
`    
model.betas[:300] = model_parms[frame_idx]
`
The first 300 parameters of the models.betas account for shape changes, parameters 300 - 400 for expression changes accordingly. So if you change the model.betas[300:400] this will change the expression. 

However, depending on the chosen expression, this might mess up the result as the expression and the speech articulation are not independent. Ideally one learns from emotional speech data how speech and emotions correlate.
