### ISSUE TITLE
The requested URL /downloads/voca/trainingdata_zip was not found on this server.

### ISSUE THREAD

**Issue by wangqianyun001** [TimoBolkart/voca#35]
Hi,

Thanks a lot for this wonderful work! 
I am trying to train voca with given dataset, however I met the problem with training data. 
After going to https://psfiles.is.tuebingen.mpg.de/downloads/voca/trainingdata_zip,
I got "The requested URL /downloads/voca/trainingdata_zip was not found on this server.". 
Is there something wrong with my network?

**Comment by TimoBolkart** [comment]
Hi, it seems the download server was down due to a power outage. It should work now again.
