### ISSUE TITLE
Implementation mistake in _validation_step function 

### ISSUE THREAD

**Issue by mrkoujan** [TimoBolkart/voca#36]
Hey,

Congratulations on this excellent work and thanks for sharing your code and results.

As far as I understand, the _validation_step funtion in the voca_model class is intended to compute the validation error conditioned on all training subjects and return the average over all. Towards that, the elements of each of the validation batch variables (processed_audio, vertices, templates, conditions) were repeated according to 'num_training_subjects' parameter. For that, the np.repeat method was used. However, given the way you create conditions (see below), the np.repeat will repeat each single element along axis 0 (as you define it in your code) a 'repeats' number of times. 

conditions = np.reshape(np.repeat(np.arange(num_training_subjects)[:,np.newaxis],
                                          repeats=self.config['num_consecutive_frames']*self.config['batch_size'], axis=-1), [-1,])

Instead, we would like to repeat the elements along axis 0 in blocks to match with 'conditions' so that each data frame is conditioned on all training subjects. Currently, for example, the first  'num_training_subjects' elements of 'conditions' are all zeros, while the first 'num_training_subjects'  elements along axis 0 of , e.g., self.speech_features, after repeating them the way you do currently, are all exactly the same. This means you will condition the same data frame repeatedly by 'num_training_subjects' on subject number 0. This will also produce wrong results when computing the velocity loss, as consequtive data frames are the same after following this way of repeatition.

Alternatively, np.tile could be use as a solution to this. For example, the new way of creating self.speech_features could be as follows:

 self.speech_features = np.expand_dims(np.tile(processed_audio, (num_training_subjects, 1, 1)), -1)

Do you agree?

**Comment by TimoBolkart** [comment]
Hey,

thank you. Yes, you are right, good catch. I just fixed it and I hope it works properly now.
