### ISSUE TITLE
Rendering texture in output video

### ISSUE THREAD

**Issue by thetobysiu** [TimoBolkart/voca#38]
Hello, I would like to know if it's possible to render a textured video instead of a pure mesh. I found from the flame project that it also exports a mesh with texture. Should I load the texture mapping every time the pyrender renders a mesh in the voca code? Thank you!

**Comment by TimoBolkart** [comment]
Sure, one easy workaround would be to assign the texture to each frame of the VOCA output and then render the textured meshes instead of the blank meshes.

**Comment by TimoBolkart** [comment]
Please check this [issue](https://github.com/TimoBolkart/voca/issues/45) to see how to create textured meshes
