### ISSUE TITLE
Training code?

### ISSUE THREAD

**Issue by g1910** [TimoBolkart/voca#4]
Hi, first of all amazing work and my condolences for the first author.

It seems that the tensorflow code for the model is not present in the repo. Can you please guide me to it or can you please make it available to try out the training?

**Comment by TimoBolkart** [comment]
Hi, thank you for your interest in VOCA. We did not release the training code yet. The code has some dependencies that we cannot release due to some licensing issues. We will try to resolve this to make the training code available as well.

**Comment by g1910** [comment]
Can you share the training, validation and test split of subjects? And also what index you used for which subject for the one-hot encoding?

**Comment by TimoBolkart** [comment]
The information about training, validation and test data splits and the ids of the training subjects for the one-hot encoding are now part of the readme

**Comment by ollieliu02** [comment]
@TimoBolkart Hi, thanks for the amazing work. 
May I follow up with the training code? Is there any progress on licensing issues? I'm just wondering do we still get the chance to see the training part. Thanks a lot!
