### ISSUE TITLE
Vocaset to training data

### ISSUE THREAD

**Issue by xiaoroubao1996** [TimoBolkart/voca#42]
Hello, I would like to know if it's possible to know how to convert Vocaset to the training data. Is there some code that you can share. It's very helpful. Thank you!

**Comment by TimoBolkart** [comment]
Hi, we provide both for dowload on the [VOCA website](https://voca.is.tue.mpg.de), VOCASET and the dataset converted to the training data. There should be no need to convert this yourself.
