### ISSUE TITLE
AttributeError: 'str' object has no attribute 'astype' resampled_audio = resampy.resample(audio_sample.astype(float), sample_rate, 16000)

### ISSUE THREAD

**Issue by barborad** [TimoBolkart/voca#44]
Hi,

I ran the process_audio function from inference.py, I got this error:

AttributeError: 'str' object has no attribute 'astype'

which occured in this line resampled_audio = resampy.resample(audio_sample.astype(float), sample_rate, 16000) from utils/audio_handler.py

Could anyone help me please?

**Comment by TimoBolkart** [comment]
Can you be more specific? Did you only run this particular process_audio function? Are you able to run the provided VOCA demo code?

**Comment by HeonKK** [comment]
I solved that problem using 

sample_rate, audio = wavfile.read(audiofile_path)

**Comment by TimoBolkart** [comment]
great thanks for the reply
