### ISSUE TITLE
Textured mesh mapping of lips is lost

### ISSUE THREAD

**Issue by alter-sachin** [TimoBolkart/voca#45]
Hello
Great work!
I have used this repo and other flame repos to create a textured mesh animation with sound.
I would request your help in the texture mapping coming out as more realistic.

![Screenshot from 2020-08-20 10-20-09](https://user-images.githubusercontent.com/7435550/90718142-d3a27080-e2ce-11ea-87a7-d5c20e075083.png)

As you can see the first image is a textured mesh and when it is animated the result is the next picture.

![Screenshot from 2020-08-20 10-20-40](https://user-images.githubusercontent.com/7435550/90718147-d8672480-e2ce-11ea-827f-f142254d1c8c.png)

As you must notice the lip region is troublesome, a particular region that should be textured like the skin get a texture of the face.
I have used the TF_FLAME repo to map textures onto all meshes generated by VOCA.

Best Regards

**Comment by alter-sachin** [comment]
Sure, I used the data in TF_FLAME with the image and the npy stored with landmarks to generate the result.

This result as you must know contains an OBJ file, an MTL file and texture file.

Now I take this result obj file and generate use voca to create a set of meshes that is animated according the the wav input.

Now in order to create a textured voice animation I take these set of meshes and run build_texture_from_image.py on all of these meshes.

Then i imported the series of meshes into blender and created a talking animation with textures.
This seemed like the only way to have a talking textured person from all the repositories related flame and voca.
I would be glad to receive your guidance and sort this issue.

**Comment by TimoBolkart** [comment]
The function build_texture_from_image.py takes an image and projects it into a mesh to create a texture map. This requires the 3D mesh and the image to be in correspondence, established by fitting the model to the image. 
Instead of building a texture for each frame of the VOCA generated sequence (which is wrong) just take the fixed texture and combine it with the VOCA generated mesh for visualization. There is no need to update the texture for every frame. Please let me know if this is unclear.

**Comment by alter-sachin** [comment]
Yes, thank you for replying.
I did realise the code was projecting that single texture onto the different meshes.

I am confused when you say "just take the fixed texture and combine it with the VOCA generated mesh for visualization" . I could not point out how to do this.

I tried using the same texture and imported it to the new OBJ's generated by VOCA but blender does not show them. On applying them manually as a image texture the results are not right. I get distorted textures

I have been trying to figure this out. Could you guide me what I am missing ?

**Comment by TimoBolkart** [comment]
Here some code that should do the job. Just specify the path of the source textured FLAME mesh (texture_mesh_fname), the FLAME texture (texture_img_fname) and the path of the VOCA result meshes. The code outputs in another folder all meshes with applied texture on.


```
import os                                                                                                                                                                                          
import glob
from psbody.mesh import Mesh                                                                                                                                                                           

# Replace the file name of the textured mesh the texture image, and the result folder of the VOCA meshes
texture_mesh_fname = 'TF_FLAME/results/imgHQ01148.obj'                                                                                                                      
texture_img_fname = 'TF_FLAME/results/imgHQ01148.png'     
voca_result_path = 'animation_output/meshes'                                                                                                                                                           

out_path = voca_result_path + '_textured'                                                                                                                                                              
if not os.path.exists(out_path): os.makedirs(out_path)                                                                                                                                                 

texture_mesh = Mesh(filename=texture_mesh_fname)                                                                                                                                                       
voca_mesh_fnames = sorted(glob.glob(os.path.join(voca_result_path, '*.obj')))                                                                                                                          

for fname in voca_mesh_fnames: 
    voca_mesh = Mesh(filename=fname) 
    voca_mesh.vt = texture_mesh.vt 
    voca_mesh.ft = texture_mesh.ft 
    voca_mesh.set_texture_image(texture_img_fname) 
    out_fname = os.path.join(out_path, os.path.splitext(os.path.basename(fname))[0] + '.obj') 
    voca_mesh.write_obj(out_fname) 
```

**Comment by Adorablepet** [comment]
@Augnine @TimoBolkart  I get textured mesh, how to generate video with audio?`reference code`? Thanks.

**Comment by Adorablepet** [comment]
@alter-sachin @TimoBolkart this is code, video can not be generated.Could you help me look at? Thanks.
``` bash
import os
import glob
import argparse
from subprocess import call
from psbody.mesh import Mesh
from psbody.mesh.meshviewer import MeshViewer

parser = argparse.ArgumentParser(description='Sequence visualization')
parser.add_argument('--sequence_path', default='./animation_output', help='Path to motion sequence')
parser.add_argument('--audio_fname', default='./audio/test_sentence.wav', help='Path of speech sequence')
parser.add_argument('--out_path', default='./animation_visualization', help='Output path')

args = parser.parse_args()
sequence_path = args.sequence_path
audio_fname = args.audio_fname
out_path = args.out_path

if not os.path.exists(args.out_path): os.makedirs(args.out_path)

img_path = os.path.join(out_path, 'img')
if not os.path.exists(img_path): os.makedirs(img_path)

mv = MeshViewer()

sequence_fnames = sorted(glob.glob(os.path.join(sequence_path, '*.obj')))
if len(sequence_fnames) == 0:
    print('No meshes found')

# Render images

for frame_idx, mesh_fname in enumerate(sequence_fnames):
    frame_mesh = Mesh(filename=mesh_fname)
    temp = mesh_fname.split('/')
   import os
import glob
import argparse
from subprocess import call
from psbody.mesh import Mesh
from psbody.mesh.meshviewer import MeshViewer

parser = argparse.ArgumentParser(description='Sequence visualization')
parser.add_argument('--sequence_path', default='./animation_output', help='Path to motion sequence')
parser.add_argument('--audio_fname', default='./audio/test_sentence.wav', help='Path of speech sequence')
parser.add_argument('--out_path', default='./animation_visualization', help='Output path')

args = parser.parse_args()
sequence_path = args.sequence_path
audio_fname = args.audio_fname
out_path = args.out_path

if not os.path.exists(args.out_path): os.makedirs(args.out_path)

img_path = os.path.join(out_path, 'img')
if not os.path.exists(img_path): os.makedirs(img_path)

mv = MeshViewer()

sequence_fnames = sorted(glob.glob(os.path.join(sequence_path, '*.obj')))
if len(sequence_fnames) == 0:
    print('No meshes found')

# Render images

for frame_idx, mesh_fname in enumerate(sequence_fnames):
    frame_mesh = Mesh(filename=mesh_fname)
    temp = mesh_fname.split('/')
    frame_mesh.set_texture_image(temp[-1][:-4] + '.png')    

    mv.set_dynamic_meshes([frame_mesh], blocking=True)

    img_fname = os.path.join(img_path, '%05d.png' % frame_idx)
    mv.save_snapshot(img_fname)

# Encode images to video

cmd_audio = []
if os.path.exists(audio_fname):
    cmd_audio += ['-i', audio_fname]
    print cmd_audio

if os.path.exists(args.out_path):
print(args.out_path)

out_video_fname = os.path.join(out_path, 'video2.mp4')
print(out_video_fname)
cmd = ['ffmpeg', '-framerate', '60', '-pattern_type', 'glob', '-i', os.path.join(img_path, '*.png')] + cmd_audio + [out_video_fname]
call(cmd)

    mv.set_dynamic_meshes([frame_mesh], blocking=True)

    img_fname = os.path.join(img_path, '%05d.png' % frame_idx)
    mv.save_snapshot(img_fname)

# Encode images to video

cmd_audio = []
if os.path.exists(audio_fname):
    cmd_audio += ['-i', audio_fname]
    print cmd_audio

if os.path.exists(args.out_path):
print(args.out_path)

out_video_fname = os.path.join(out_path, 'video2.mp4')
print(out_video_fname)
cmd = ['ffmpeg', '-framerate', '60', '-pattern_type', 'glob', '-i', os.path.join(img_path, '*.png')] + cmd_audio + [out_video_fname]
call(cmd)
```

**Comment by TimoBolkart** [comment]
I added a demo to the VOCA repository for providing a texture optionally to the inference code. Running this outputs textured meshes and renders the textured sequence.
