### ISSUE TITLE
pyrender: Failed rendering frame

### ISSUE THREAD

**Issue by Augnine** [TimoBolkart/voca#46]
I follow the README.md. But in the Render sequence

python visualize_sequence.py --sequence_path './FLAME_eye_blink/meshes' --audio_fname './audio/test_sentence.wav' --out_path './FLAME_eye_blink'

The srceen print
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame
pyrender: Failed rendering frame

**Comment by Passionatecricketer** [comment]
Hi @Augnine did you find a solution?
I was working on voca and same issue came when I ran python run_voca.py and only audio is saved in the animation output folder and meshes are stored seperately in meshes folder
I would like to know what am I doing wrong here

**Comment by Adorablepet** [comment]
@TimoBolkart I have same issue. How to deal with? Thanks.

**Comment by TimoBolkart** [comment]
Thank you for your interest in VOCA @Augnine @Passionatecricketer and @Adorablepet, the problem seems to be with the actual rendering rather than the VOCA mesh generation. There had been several attempts to overcome the rendering problems, maybe check [this issue](https://github.com/TimoBolkart/voca/issues/29) for some possible solutions. Please provide some feedback if any of these things work for you. 
An alternative is to use another rendering framework. I am happy to support replacing pyrender by something more reliable if there are any good suggestions

**Comment by Passionatecricketer** [comment]
Hi @TimoBolkart I tried the solutions provided in the issue that you mentioned. But none of them seem to work as I am currently working on debian and there are some issues with regards to making build of osmesa. I'll update once I get a workaround. Meanwhile if someone has any another solution please let me know.
Thanks for the reply @TimoBolkart !

**Comment by TimoBolkart** [comment]
One option could be to just replace pyrender with some other rendering framework like [Tensorflow Graphics](https://github.com/tensorflow/graphics) or [DIRT](https://github.com/pmh47/dirt) or any other renderer. I have not looked into those so I don't know what are their pitfalls and how difficult they are to integrate.

**Comment by Passionatecricketer** [comment]
Ok. Thanks for the idea. I'll try it and update the thread if something works out

**Comment by TimoBolkart** [comment]
Great, thank you. If you find any good solution, I would be happy to adapt the repository to resolve this rendering issue

**Comment by TimoBolkart** [comment]
Adding following lines to the rendering.py seems to solve the problem for some people:
```
import os
os.environ['PYOPENGL_PLATFORM'] = 'egl' # Uncommnet this line while running remotely
```
I updated the script accordingly

**Comment by a35026** [comment]
Getting this output with the latest default configuration: [https://imgur.com/a/alRE8Zm](https://imgur.com/a/alRE8Zm)

Texturized animation showed same warnings but generated just black frames from np.zeroes
Interesting that it worked only when I had added the same snippet `os.environ['PYOPENGL_PLATFORM'] = 'egl'` to `visualize_sequence.py` not just to `rendering.py`
But there also were 3 dropped frames, you can notice them here:
[https://imgur.com/a/pAnek7R](https://imgur.com/a/pAnek7R)

Ubuntu 16.04, CUDA 10.2, Nvidia: 440.59, python 3.6.11, pyrender 0.1.43, trimesh 3.8.8
@TimoBolkart could you please share pyrender and trimesh versions you use for animation?

**Comment by abhinavsp0730** [comment]
> 
> 
> Getting this output with the latest default configuration: https://imgur.com/a/alRE8Zm
> 
> Texturized animation showed same warnings but generated just black frames from np.zeroes
> Interesting that it worked only when I had added the same snippet `os.environ['PYOPENGL_PLATFORM'] = 'egl'` to `visualize_sequence.py` not just to `rendering.py`
> But there also were 3 dropped frames, you can notice them here:
> https://imgur.com/a/pAnek7R
> 
> Ubuntu 16.04, CUDA 10.2, Nvidia: 440.59, python 3.6.11, pyrender 0.1.43, trimesh 3.8.8
> @TimoBolkart could you please share pyrender and trimesh versions you use for animation?

Hi, @a35026 I've seen your generated video. Would you please tell me how you're able to produce the video with a real face and not with the default 3d avatar of voca?

**Comment by hammad93** [comment]
I had the same error on a remote instance of Google Colab, and instead of using EGL I installed OSMesa per https://pyrender.readthedocs.io/en/latest/install/index.html#installmesa

I then set the environment variables inside the `visualize_sequence.py` and `rendering.py`

**Comment by dozen12** [comment]
Thank you so much.. @hammad93

**Comment by zhanghm1995** [comment]
I found one solution, downgrading your openGL version:
```
pip install pyopengl==3.1.0
```
When I using the above 3.1.0 pyopengl version, I got everything works well.

**Comment by Nina-yang** [comment]
change 'egl' to os.environ['PYOPENGL_PLATFORM'] = 'osmesa' works for me.

**Comment by wsywsywsywsywsy979** [comment]
> I found one solution, downgrading your openGL version by using:
> 
> ```
> pip install pyopengl==3.1.0
> ```
> 
> When I using the above 3.1.0 pyopengl version, I got everything works well.

why I run “run_voca” still report errors “pyrender: Failed rendering frame”？I have try many solution in "issue" but still haven't solve it.

**Comment by QifengDai** [comment]
I solved the problem by just commenting out the `os.environ['PYOPENGL_PLATFORM']='egl'` in `rendering.py`.

**Comment by QifengDai** [comment]
Quite the opposite, I solved the problem by just commenting out the `os.environ['PYOPENGL_PLATFORM']='egl'` in `rendering.py`.
