### ISSUE TITLE
How to create 3D textured model from Ringnet for using it in VOCA

### ISSUE THREAD

**Issue by 12345data** [TimoBolkart/voca#48]
I was trying some experiments with VOCA. When I tried the Ringnet repository many of the meshes looked similar with another. Hence as you know, the texture is really important for identifying a person. How can I add texture to the meshes for using them in VOCA. I have tried with TF_FLAME for creating texture for the mesh using the image file but it was not usable in VOCA. Can you suggest how I can do this?
It will be really grateful if you can help me with this. Thank you

**Comment by TimoBolkart** [comment]
I added an option to the VOCA repository to pass a texture. VOCA then outputs animated meshes with this texture applied and renders the textured meshes.
