### ISSUE TITLE
basic information about texture

### ISSUE THREAD

**Issue by Adorablepet** [TimoBolkart/voca#49]
I run voca, visualize the meshes with a pre-defined texture (obtained by fitting FLAME to an image using `TF_FLAME`), the video is generated.The `texture_mesh.png` does not seem to contain texture information about the teeth.If I need to add tooth texture to an existing video, what should I do, thanks.
[video.zip](https://github.com/TimoBolkart/voca/files/5274860/video.zip)

**Comment by TimoBolkart** [comment]
Teeth are to date not part of the FLAME geometry, hence there is not way of recovering teeth in form of a simple texture
