### ISSUE TITLE
add eyeblink to texture data in animation

### ISSUE THREAD

**Issue by rkolaf** [TimoBolkart/voca#51]
hi,
First of all, thank you for this work. 
I was able to make the eye blinking possible with the created 3d mesh, but don't know how to perform the same in the obj data along with the texture content. I was able to create the animation with the texture data but I need to make the eye blinking also work in that animation, please do help.
Thanks

**Comment by TimoBolkart** [comment]
Hi, we provide a demo to add blinks to the geometry. Adding a fixed texture should do the job. Can you please be more specific on what is your problem and maybe show the video you get?

**Comment by rkolaf** [comment]
hi, thanks for your reply. The steps we have done are: first got the obj file from RingNet and then converted to ply file. we were able to perform the eyeblink operation with this obj file.
we used the command:
_python run_voca.py --tf_model_fname './model/gstep_52280.model' --ds_fname './ds_graph/output_graph.pb' --audio_fname './audio/test_sentence.wav' --template_fname './template/FLAME_sample.ply' --condition_idx 3 --uv_template_fname './template/texture_mesh.obj' --texture_img_fname './template/texture_mesh.png' --out_path './animation_output_textured'_
 Then we used tf flame repo to get the texture file and the corresponding obj file. and hence we were able to get the animation with texture data(mtl file). But we cannot include the eyeblink information to this texture data.
we use the command: _python edit_sequences.py --source_path './animation_output_textured/meshes' --out_path './FLAME_eye_blink' --flame_model_path  './flame/generic_model.pkl' --mode blink --num_blinks 2 --blink_duration 15_
then we use the command:
_python visualize_sequence.py --sequence_path './FLAME_eye_blink/meshes' --audio_fname './audio/test_sentence.wav' --out_path './FLAME_eye_blink'_
 when  we try to do the eyeblink operation it shows the animation result without the texture data. 
Thanks in advance.

**Comment by TimoBolkart** [comment]
Hi, that sounds reasonable. Can you show the resulting animation or a picture of it do demonstrate the issue you are facing?

**Comment by rkolaf** [comment]
Hi, sorry for the late reply. We were able to get the textured animated video "video.mp4" in the zip file attached below. But  we are not able to get the eyeblink operation in the textured mesh. When running the _python visualize_sequence.py --sequence_path './FLAME_eye_blink/meshes' --audio_fname './audio/test_sentence.wav' --out_path './FLAME_eye_blink'_ for the textured meshes, it just shows the eyeblink operation in the mesh without the texture data as shown as in the video "video_mesh.mp4" in the attached zip file. What did I miss? 
Thanks in advance.
[video.zip](https://github.com/TimoBolkart/voca/files/5338508/video.zip)

**Comment by 12345data** [comment]
@TimoBolkart @rkolaf I also got the same result as mentioned by @rkolaf. While trying to add eye blink on the textured data, result was only the animation without textured. How can this be done? What all changes need to be done for that?

**Comment by TimoBolkart** [comment]
Sorry for the late reply, you are right, edit_sequences.py and visualize_sequence.py unfortunately ignore the texture of the meshes. An easy workaround is to run the visualize_sequence.py with the  flags `--uv_template_fname` and `--texture_img_fname` as you also do for the run_voca.py demo. This adds the fixed texture then to the meshes before rendering. I hope that solves your problems @rkolaf and @12345data

**Comment by 12345data** [comment]
Works great. Thanks for the help.

**Comment by TimoBolkart** [comment]
Thanks for the feedback

**Comment by cssddnnc9527** [comment]
@rkolaf hi, thanks for your issue. According this, i can also add texture to the animation. But my problem is that the blink action is very slight, the eyes don't close at all while blinking. Have you ever met this problem, if yes, how did you resolve it? thanks  in advance.
