### ISSUE TITLE
I can not download  MPI-IS/VOCA, MPI-IS/FLAME, and MPI-IS/VOCASET.

### ISSUE THREAD

**Issue by wanghuogen** [TimoBolkart/voca#58]
Dear authors, I can not download MPI-IS/VOCA, MPI-IS/FLAME, and MPI-IS/VOCASET. When I try to download these data, the websit print out "We're sorry, but something went wrong. The issue has been logged for investigation. Please try again later." How can I fix this problem? Thank you.

**Comment by TimoBolkart** [comment]
Thanks for reporting this issue. There is an issue with our web server and our IT is on it. I hope it will be fixed soon.

**Comment by philippbb** [comment]
Hello. Is it possible to upload it somewhere else? Its still unavailable. Thank you very much.
