### ISSUE TITLE
can not find palce to download data

### ISSUE THREAD

**Issue by fortuneko** [TimoBolkart/voca#6]
Hi, 
   i am very interested with the project and want to have a try. as described in the readme ,"Download the trained VOCA model, audio sequences, and template meshes from MPI-IS/VOCA."
but I found no data the target link at https://voca.is.tue.mpg.de/ or at https://ps.is.tuebingen.mpg.de/publications/voca2019
  could you please provide a more specific url to get the data? thank you very much

**Comment by TimoBolkart** [comment]
Hi,
thank you for your interest in VOCA. The data are available under https://voca.is.tue.mpg.de/
You are required to sign up and agree to the license file in order to access the data.

**Comment by fortuneko** [comment]
thanks ,it works
