### ISSUE TITLE
About different version of deepspeech model

### ISSUE THREAD

**Issue by kuanxin** [TimoBolkart/voca#63]
If I want to use a different version of deepspeech model (v0.9.2), do I need to retrain VOCA?

Many thanks!

**Comment by TimoBolkart** [comment]
Yes, exchanging the deepspeech version will need to retrain VOCA.

When trying to replace the used deepseech version by the newest one back in 2019, we encountered some problems with it. Mozilla changed the input structure which made a direct usage difficult. I don't know how this is with the currently newest version
