### ISSUE TITLE
How to convert model into pb file which can be used in C?

### ISSUE THREAD

**Issue by drrobincroft** [TimoBolkart/voca#69]
As above, for more efficiency, we have to use C to use the VOCA model.
So it is necessary to convert the model into pb file.
However, there is some error for this like:
2 root error(s) found.
  (0) Invalid argument: The second input must be a scalar, but it has shape [1]
         [[{{node VOCA/SpeechEncoder/batch_norm_1/cond/Switch}}]]
  (1) Invalid argument: The second input must be a scalar, but it has shape [1]
         [[{{node VOCA/SpeechEncoder/batch_norm_1/cond/Switch}}]]
         [[_arg_VOCA/Inputs_encoder/condition_subject_id_0_1/_3]]
0 successful operations.
0 derived errors ignored.
How to fix it?

**Comment by drrobincroft** [comment]
Maybe I have to find another way to fix the problem.

**Comment by liushao** [comment]
Dear drrobincroft,  Can you share the way how to convert the model into pb file? Thanks
