### ISSUE TITLE
I get the OpenGL Error when i run visualize_sequence.py

### ISSUE THREAD

**Issue by Masquerades2015** [TimoBolkart/voca#7]
whenI run visualize_sequence.py, then the console  immediately printed the following error. Does this affect the program?

OpenGL test failed: 
	stdout: failure

	stderr: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling

**Comment by ZHANG-SHI-CHANG** [comment]
> whenI run visualize_sequence.py, then the console immediately printed the following error. Does this affect the program?
> 
> OpenGL test failed:
> stdout: failure
> 
> ```
> stderr: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling
> ```

how can you process it? I meet it too

**Comment by wjy5446** [comment]
I solved this problem!!
I executed below command
```
sudo apt-get install freeglut3-dev
```
