### ISSUE TITLE
The training data is not downloadable, please check it

### ISSUE THREAD

**Issue by drrobincroft** [TimoBolkart/voca#71]
The link https://psfiles.is.tuebingen.mpg.de/downloads/voca/trainingdata_zip leads to Download denied page again and again, no matter how many times I signed in and tried. 
Does that something go wrong?

**Comment by TimoBolkart** [comment]
These links are protected to be only accessible from the website. The privacy settings of the browser sometimes give an access denied error, please try again with settings "keep history" enabled.

**Comment by jiawenzzz** [comment]
Hi, I tried to download dataset throught the website, but still met this access denied error. I tried three browsers with 'keep history' enanbled. Also, I once successfully accessed dataset in July, and then the denied page showed up since August. 
Any suggestions? Thanks.
