### ISSUE TITLE
result video flickering problem!

### ISSUE THREAD

**Issue by Enin** [TimoBolkart/voca#76]
Hello! 
Thanks to you're great research.

I have a problem with result video. It successfully generated but video was keep flickering.

https://user-images.githubusercontent.com/26217904/131309416-fd984de6-562d-4088-ad6b-6404037d4bab.mp4

I used this two scripts which gave in main page and not changed source code.

python run_voca.py --tf_model_fname './model/gstep_52280.model' --ds_fname './ds_graph/output_graph.pb' --audio_fname './audio/test_sentence.wav' --template_fname './template/texture_mesh.obj' --condition_idx 3 --out_path './animation_output'

python run_voca.py --tf_model_fname './model/gstep_52280.model' --ds_fname './ds_graph/output_graph.pb' --audio_fname './audio/test_sentence.wav' --template_fname './template/source3.obj' --condition_idx 3 --uv_template_fname './template/source3.obj' --texture_img_fname './template/source3.png' --out_path './animation_output_textured'

please check this video and tell me how can I fix this problem.

Thank you!

**Comment by TimoBolkart** [comment]
Running the script outputs a set of meshes, one for each frame. If these are correct, then check the renderings for each frame to see if this is a rendering problem, or a problem of the final encoding into a video. I have not seen such kind of flickering before

**Comment by Enin** [comment]
I checked generated meshes and they were correct i think. maybe it is rendering or encoding problem (pyrender maybe) I will check this part, thank you for answer.

**Comment by TimoBolkart** [comment]
That is interesting, I wonder why this would cause flickering as the light setup for every frame is identical. But good that you solved it.
