### ISSUE TITLE
How do I use with python

### ISSUE THREAD

**Issue by 007rohitSaini** [TimoBolkart/voca#77]
I want to make a chat bot with VOCA.
with python.
so how do I make it real-time and do I need to download 71 gb audio sequential for it.

**Comment by TimoBolkart** [comment]
VOCA uses DeepSpeech as its backbone, which uses audio windows to generate 3D faces. This aggregates some past and future audio information to generate one frame. In this setting, it is not trivial to make it interactive. The implementation of the DeepSpeech as feature extractor also limits the execution time.
