### ISSUE TITLE
Audio and the mouth are not synced

### ISSUE THREAD

**Issue by CharlesShang** [TimoBolkart/voca#8]
My sincere condolences for Daniel Cudeiro, and amazing works!

I have a problem with the generated video. The audio and mouth seem un-synced, e.g, the speech is finished, but the mouth is still moving. 
I followed the instruction to install the model, and there were no errors prompted during the installation and inference. 
I'm wondering if it is because of some setting errors in the code, or the model itself? 

My workarounds: 
1. switching to different input audio.
2. changing different frame rates in `visualize_sequence.py` line 62 `... '-framerate', '60', ...` to `30`, `40`, `50`.

**Comment by TimoBolkart** [comment]
Thank you for your interest in VOCA. 

> I have a problem with the generated video. The audio and mouth seem un-synced, e.g, the speech is finished, but the mouth is still moving.

Together with the model and code, we provide a sample audio sequence. Does this problem also occur with this provided audio? 

Changing the frame rates will not provide you a reasonable result as the model was explicitly trained to output meshes at 60 fps. Can you run VOCA please without any code changes and output the rendered sequence and send this via email to tbolkart (at) tuebingen (dot) mpg (dot) de

**Comment by CharlesShang** [comment]
@TimoBolkart Sure!

**Comment by CharlesShang** [comment]
Hi, @TimoBolkart, 
My fault, the un-synced video was generated with an audio, but rendered with a different audio. 
Sorry for bothering you.
