### ISSUE TITLE
Interpertation of %M in the camera calibration files

### ISSUE THREAD

**Issue by Muaz231** [TimoBolkart/voca#88]
Hi, Can anyone help me in understanding what does %M and the three rows of numbers mean in the camera calibration files? Is it a matrix related to some camera related projection matrix?

Thanks!

(Sample image attached)

![image](https://user-images.githubusercontent.com/85618702/145930771-63e5dac5-2b9e-4f3d-ba7b-9612c0a1a412.png)

**Comment by chaiyujin** [comment]
I attempted to project 3D mesh onto image with given camera calibration.
I found that M is rotation matrix and following XYZ are the translation of camera extrinsics (R, t).

**Comment by Muaz231** [comment]
@chaiyujin Did you try to generate some depth images from the 3D mesh? Also, which library you use for projecting the 3D mesh to an image? Thanks!

**Comment by chaiyujin** [comment]
@Muaz231 Didn't try that. The 3D meshes are already in world coordinates, the `z` component of each vertex can be treated as depth, but sparse. You can sythesize depth image by rendering 3D meshes onto image plane, with the original `z` component (value from .ply, without any matrix operation) as "color" value.
I use numpy to compute matrices and OpenGL to render.

**Comment by Muaz231** [comment]
@chaiyujin Thanks!
