### ISSUE TITLE
How manually control expression ??

### ISSUE THREAD

**Issue by yjhong89** [TimoBolkart/voca#89]
Dear author.

Thank you for great work.

I am currently seeking a way how manually control expression (eye blink, mouth close... ) with FLAME parameters. 
I found that getting an eye blink by chaning FLAME's expression parameters in "edit_sequence.py", but I also wonder how we could get ["blink_eye_beta"](https://github.com/TimoBolkart/voca/blob/7bfd21ccdefcf284ba784f55eea57f9d5ab11d00/edit_sequences.py#L69)

Can you give me more detail how I can manually control expression with FLAME parameters  as VOCA did an eye_blink ?

Thank you!

**Comment by TimoBolkart** [comment]
For the eye blink, we directly take the FLAME expression blendshapes (weighted by the eye blink parameters) and add them to the VOCA output mesh. This is possible as VOCA animates the mouth / lower face half, while the eye blink is in the upper part. We also show how to change the face identity by using FLAME's identity shape blendshapes. 
Generally editing the expressions is more complicated as they affect the mouth and therefore interfere with VOCA's generated mouth articulation.
