### ISSUE TITLE
I get the “X Error of failed request” when i run visualize_sequence.py

### ISSUE THREAD

**Issue by MISSXUAN0** [TimoBolkart/voca#9]
When i run visualize_sequence.py，i got this error：
X Error of failed request:  BadRequest (invalid request code or no such operation)
  Major opcode of failed request:  146 (GLX)
  Minor opcode of failed request:  187 ()
  Serial number of failed request:  135
  Current serial number in output stream:  135
It's the first time I've had this problem，I don't know how it started. Can someone help me？

**Comment by michaelzhou0723** [comment]
I got the same error. How did you solve it? @MISSXUAN0
