### ISSUE TITLE
Assign random shape parameters

### ISSUE THREAD

**Issue by yangdaowu** [TimoBolkart/voca#93]
Hello, I want to consult the betas [: 100] is how to set up. 

for i in range(num_samples):
    # Assign random shape parameters.
    # Beware changing expression parameters (i.e. betas[300:400]) or pose will result in meshes that cannot be used
    # as template for VOCA as VOCA requires "zero pose" templates in neutral expression
    flame_model.betas[:100] = np.random.randn(100) * 1.0

    # Output mesh in "zero pose"
    Mesh(flame_model.r, flame_model.f).write_ply(out_fname(i+1))

**Comment by TimoBolkart** [comment]
What do you mean with you want to consult the betas? What do you want to do?

**Comment by TimoBolkart** [comment]
The edit_sequences script demonstrates how to alter face shape of a sequence, if this is what you intend to do.
