### ISSUE TITLE
How could i get apple arkit 52 blendshapes?

### ISSUE THREAD

**Issue by Justpenz233** [TimoBolkart/voca#97]
How could i get apple ARkit 52 blendshapes from the VOCA net-work output ?
Should I train another net to do the mapping (from 5093 to 52) ?

**Comment by TimoBolkart** [comment]
One could output a lot of meshes from Apple's ARkit with different expressions, fit FLAME to these, and learn a mapping between FLAME's parameter space and the ARkit blendshapes.
