### ISSUE TITLE
Are vertices used in training regular vertices or transformed vertices?

### ISSUE THREAD

**Issue by ulucsahin** [TimoBolkart/voca#98]

**Comment by TimoBolkart** [comment]
Can you please specify what you refer to as regular or transformed vertices in this case?
VOCA is trained on data that are registered to a common mesh topology (i.e., FLAME meshes), and all meshes are in "zero pose", which means effects of global rotation / orientation and head rotation around the neck are factored out. 
Does this answer your question?

**Comment by ulucsahin** [comment]
This answers my question, thank you. 

On some works there are camera parameters and either perspective or orthogonal transformations are computed based on FLAME vertices. Now I understand that this is not used in VOCA and vertices are used without such transformations.
